transformations:
  - frame_id: charger
    id: camera_color_optical_frame
    transform:
      - -0.23
      - -0.025
      - 0.232
      - 0.5
      - -0.5
      - 0.5
      - -0.5
  # temporarily till pf works
  - frame_id: map
    id: nathan
    transform:
      - 0.45715
      - -3.4502
      - -1.5521
      - 0.0
      - 0.0
      - 0.0
      - 1.0
# temporarily till pf works
#- frame_id: map
#  id: nathan
#  transform:
#    - 0.45715
#    - -3.4502
#    - -1.5521
#    - 0.0
#    - 0.0
#    - 0.0
#    - 1.0