---
transformations:
#  - id: 'aptag_0'
#    frame_id: 'opt_cam'
#    matrix:
#      - [0.0, 1.0, 0.0, 1.0]
#      - [0.0, 0.0, -1.0, 0.0]
#      - [-1.0, 0.0, 0.0, 0.0]
#      - [0.0, 0.0, 0.0, 1.0]
  - id: 'camera_color_optical_frame'
    frame_id: 'map'
    matrix:
      - [1.0, 0.0, 0.0, 0.0]
      - [0.0, 0.0, 1.0, 0.0]
      - [0.0, -1.0, 0.0, 0.11]
      - [0.0, 0.0, 0.0, 1.0]
  - id: 'aptag_0'
    frame_id: 'map'
    matrix:
      - [ 0.0, 1.0, 0.0, -0.22 ]
      - [ -1.0, 0.0, 0.0, 2.08 ]
      - [ 0.0, 0.0, 1.0, 0.55 ]
      - [ 0.0, 0.0, 0.0, 1.0 ]
  - id: 'aptag_2'
    frame_id: 'map'
    matrix:
      - [ 0.0, 1.0, 0.0, 1.08 ]
      - [ -1.0, 0.0, 0.0, 1.65 ]
      - [ 0.0, 0.0, 1.0, 0.23 ]
      - [ 0.0, 0.0, 0.0, 1.0 ]
  - id: 'aptag_13'
    frame_id: 'map'
    matrix:
      - [ -1.0, 0.0, 0.0, 1.66 ]
      - [ 0.0, -1.0, 0.0, 0.6 ]
      - [ 0.0, 0.0, 1.0, 0.35 ]
      - [ 0.0, 0.0, 0.0, 1.0 ]